import {ensureError, HttpStatus, log, randomString, SelectFrom} from '@augment-vir/common';
import fastifyWs from '@fastify/websocket';
import {GenericServiceImplementation, ServiceImplementation} from '@rest-vir/implement-service';
import {type FastifyInstance} from 'fastify';
import {HandleRouteOptions} from '../handle-request/endpoint-handler.js';
import {handleRoute} from '../handle-request/handle-route.js';
import {preHandler} from '../handle-request/pre-handler.js';

declare module 'fastify' {
    interface FastifyRequest {
        restVirContext:
            | {
                  /**
                   * {@link attachService} can be called multiple times. Each time it is called, a
                   * new `AttachId` is generated and contexts generated by that attachment are
                   * stored in the request under that id.
                   */
                  [AttachId in string]: {
                      context: unknown;
                      requestData: unknown;
                      protocols: unknown;
                  };
              }
            | undefined;
    }
}

/**
 * Attach all handlers for a {@link ServiceImplementation} to any existing Fastify server.
 *
 * @category Run Service
 * @category Package : @rest-vir/run-service
 * @example
 *
 * ```ts
 * import fastify from 'fastify';
 *
 * const server = fastify();
 *
 * attachService(service, myServiceImplementation);
 *
 * await server.listen({port: 3000});
 * ```
 *
 * @package [`@rest-vir/run-service`](https://www.npmjs.com/package/@rest-vir/run-service)
 */
export async function attachService(
    server: Readonly<FastifyInstance>,
    service: Readonly<
        SelectFrom<
            GenericServiceImplementation,
            {
                webSockets: true;
                endpoints: true;
                serviceName: true;
                createContext: true;
                serviceOrigin: true;
                requiredClientOrigin: true;
                logger: true;
            }
        >
    >,
    options: Readonly<HandleRouteOptions> = {},
): Promise<void> {
    try {
        const attachId = randomString(32);

        if (!server.hasRequestDecorator('restVirContext')) {
            server.decorateRequest('restVirContext');
        }
        if (!server.hasRequestDecorator('ws')) {
            await server.register(fastifyWs);
        }

        server.addHook('preValidation', async (request, response) => {
            try {
                await preHandler(request, response, service, attachId, options);
            } catch (error) {
                log.if(!!options.debug).error(error);
                service.logger.error(ensureError(error));
                if (options.throwErrorsForExternalHandling) {
                    throw error;
                } else if (!response.sent) {
                    response.statusCode = HttpStatus.InternalServerError;
                    response.send();
                }
            }
        });

        Object.entries(service.webSockets).forEach(
            ([
                path,
                webSocketDefinition,
            ]) => {
                server.get(path, {websocket: true}, async (webSocket, request) => {
                    await handleRoute(
                        webSocket,
                        request,
                        undefined,
                        webSocketDefinition,
                        attachId,
                        options,
                    );
                });
            },
        );

        Object.entries(service.endpoints).forEach(
            ([
                path,
                endpoint,
            ]) => {
                server.all(path, async (request, response) => {
                    await handleRoute(undefined, request, response, endpoint, attachId, options);
                });
            },
        );
        /* node:coverage ignore next 4: this is just here to cover edge cases. */
    } catch (error) {
        log.if(!!options.debug).error(error);
        throw error;
    }
}
